require:
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - '**/bin/**/*'
    - '**/node_modules/**/*'
    - '**/pkg/**/*'
    - '**/tmp/**/*'
    - '**/vendor/**/*'
