name: CI

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
    - uses: codecov/codecov-action@v3
